source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RisingSSR/RisingCyxbsSepc.git'

use_frameworks!

platform :ios, '11.0'

target 'CyxbsScheduleCourse_Example' do
  pod 'CyxbsScheduleCourse', :path => '../'

  target 'CyxbsScheduleCourse_Tests' do
    inherit! :search_paths

    
  end
end
