use_frameworks!

platform :ios, '10.0'

target 'CyxbsScheduleCourse_Example' do
  pod 'CyxbsScheduleCourse', :path => '../'

  target 'CyxbsScheduleCourse_Tests' do
    inherit! :search_paths

    
  end
end
